searchTree
psiblvdegod/homework pull request #18
Opened 2024-11-19 17:35 UTC by psiblvdegod

2024-12-31 09:18 UTC, yurii-litvinov requested changes
Комментарии к коммитам ужасны. Рекомендую https://www.conventionalcommits.org/en/v1.0.0/.

2024-12-31 09:18 UTC, yurii-litvinov commented on searchTree/main.c
> +    treeTests(&errorCode);
Если тесты не прошли, надо возвращать не 0

2024-12-31 09:18 UTC, yurii-litvinov commented on searchTree/main.c
> +    Node *root = NULL;
Я как пользователь не хочу ничего знать про root, я хочу словарь с возможностью хранить значение по ключу

2024-12-31 09:18 UTC, yurii-litvinov commented on searchTree/main.c
> +    while (userQuery) {
```suggestion
    while (userQuery != 0) {
```
Избегайте неявных кастов

2024-12-31 09:18 UTC, yurii-litvinov commented on searchTree/queryProcessing.c
> +    const int key = (int)strtol(buffer, NULL, 10);
scanf("%d"... сделал бы всю работу за Вас

2024-12-31 09:18 UTC, yurii-litvinov commented on searchTree/queryProcessing.c
> +void queryProcessing(Node **root, const int userQuery, int *errorCode) {
Называйте функции глаголом в повелительной форме. processQueue, например

2024-12-31 09:18 UTC, yurii-litvinov commented on searchTree/tests.c
> +        return;
Память утечёт

2024-12-31 09:18 UTC, yurii-litvinov commented on searchTree/tree.c
> +    node->value = value;
Лучше копировать в дерево значение, так вызывающий не будет обязан выделять память, и можно будет использовать строковые литералы

2024-12-31 09:18 UTC, yurii-litvinov commented on searchTree/tree.c
> +        node->value = newNode->value;
Так утечёт память, выделенная под старое значение

2024-12-31 09:18 UTC, yurii-litvinov commented on searchTree/tree.c
> +        free(newNode);
Если бы insertRecursive принимал не newNode, а value, можно было бы избежать преждевременного создания узла и удаления, если узел не нужен

2024-12-31 09:18 UTC, yurii-litvinov commented on searchTree/tree.c
> +        free(node);
value ещё надо удалить

2024-12-31 09:18 UTC, yurii-litvinov commented on searchTree/tree.c
> +    free(node);
И тут

2024-12-31 09:18 UTC, yurii-litvinov commented on searchTree/tree.h
> +} Position;
Оно вроде нигде не используется

2024-12-31 14:59 UTC, psiblvdegod commented on searchTree/queryProcessing.c
> +    const int key = (int)strtol(buffer, NULL, 10);
если использовать scanf("%d",<...>), IDE выдает предупреждение:
'scanf' used to convert a string to an integer value, but function will not report conversion errors; consider using 'strtol' instead
и, если ввести какие-нибудь символы, кроме цифр, программа зависает в бесконечном цикле

2025-01-02 13:38 UTC, psiblvdegod commented on searchTree/tree.c
> +        free(newNode);
В функции deleteRecursive() вызывается insertRecursive(), чтобы не потерять поддеревья:
Node *children = insertRecursive(node->leftChild, node->rightChild);
Затем children возвращается. Не очень понятно, как грамотно вернуть в дерево оба дочерних поддерева, не выполняя вставку одного относительно второго. Поэтому здесь использовал newNode, а не value и key.

2025-01-11 17:25 UTC, yurii-litvinov approved these changes
Окей, зачтена

2025-01-11 17:25 UTC, yurii-litvinov commented on searchTree/tests.c
> +    root = insertInTree(root, "111", 1, &errorCode);
В случае провала insertInTree утечёт уже выделенная память

2025-01-11 17:25 UTC, yurii-litvinov commented on searchTree/tree.c
> +        free(temp);
```suggestion
        free(node->value);
        node->value = newNode->value;
```

2025-01-11 17:25 UTC, yurii-litvinov commented on searchTree/tree.c
> +        free(newNode);
Окей, хотя есть другой способ удаления (Ваш, кстати, вроде как способствует вытягиванию дерева в высоту, в отличие от каноничного)

2025-02-08 12:54 UTC, merged